### ISSUE TITLE
Enviar sol·licitud revisió al professor

### ISSUE THREAD

**Issue by jmirfern** [jmirfern/data-lifecycle-pr1#11]

**Comment by mp334t1** [comment]
Ja està el correu enviat, adjunte còpia d'aquest:
Assumpte: PRA1: Web scraping
Cos: Bona nit, soc Dario Cabrera, alumne de M2.951 - Tipologia i cicle de vida de les dades, t'adjunte en aquest correu l'enllaç del Git del nostre treball, on els membres d'aquest son:

Jonathan Mir Fernández-Aramburu [jmirfern@uoc.edu](mailto:jmirfern@uoc.edu)
Dario Cabrera Gurillo [dacagu@uoc.edu](mailto:dacagu@uoc.edu)

enllaç: https://github.com/jmirfern/data-lifecycle-pr1

Moltes gràcies per tot.
