### ISSUE TITLE
Error a exportar fitxer

### ISSUE THREAD

**Issue by jmirfern** [jmirfern/data-lifecycle-pr1#13]

**Comment by mp334t1** [comment]
Ja ho tinc clar com s'ha d'executar el codi, podem posar, perquè guarde bé el document, el següent cas:
`ruta = os.path.join(output_path, 'data', 'comparacio_cobertures_auto.csv')`
Posaria en el document, que per a executar el codi seria necessari, en la terminal, incorporar el següent:
`Python3 "ruta"/get_insurance_coverages.py --export_path "ruta"`
O, en cas que no s'incorpore aquesta línia de codi en la terminal, canviant la funció main():
```
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--export_path", help="Entra la ruta per exportar el fitxer de sortida csv")
    args = parser.parse_args()
    if args.export_path is None:
        output_path = os.getcwd()
    else:
        output_path = args.export_path
    webscrap_insurance_webs(output_path)
```
Ja que el professor, no sé si pot executar bé el codi, ja m'ho diràs :D.

**Comment by jmirfern** [comment]
sí, em sembla perfecte. Si fas el canvi, executa i prova que funcioni correctament. Pots fer-lo sobre la mateixa branch i fem el pull, merci!!

**Comment by mp334t1** [comment]
Ja estan els canvis realitzats, si pots realitzar el pull ja estaria tot, merci.
