### ISSUE TITLE
Pandas Pre-processing

### ISSUE THREAD

**Issue by jmirfern** [jmirfern/data-lifecycle-pr1#4]
Un cop treballades les condicions, caldrà fer un pre-processament tal que el dataset final sigui el següent:

| company | paquet | garantia | cobertura |
|--|--|--|--|
| Zurich | Responsabilidad Civil obligatoria y voluntaria | A terceros | Incluida |
| Zurich | Responsabilidad Civil obligatoria y voluntaria | A terceros Completo | Opcional |

**Comment by jmirfern** [comment]
Hola @mp334t1, el profesor ja ha confirmat que el nostre plantejament és correcte:

> Hola Jonathan,
>
> Si teniu problemes de compliment de GDPR us recomano que us decidiu per la segona opció que em comentes. I sí, és > correcte! Penseu que teniu total llibertat alhora d'escollir el lloc web, qualsevol opció que us resulti interessant és bona > opció! :) 
>
> Salutacions,

**Comment by jmirfern** [comment]
Hauríem d'incloure `date` i `companyia`

```python
from datetime import datetime
df["company"]="Mapfre"
df["date"]=datetime.now
```

**Comment by mp334t1** [comment]
Ja està el panda realitzat, actualment hi ha 5 asseguradores: Catalana Occidente, Direct Seguro, MMT Seguros, RACC i Seguros Bilbao. Tenia també la Mútua Madrileña, però en revisar el csv he vist que cal realitzar alguns canvis. En aquests ja es pot treballar.
